### ISSUE TITLE
Interpretación de summary_results (Aligned reads < Assigned reads ?)

### ISSUE THREAD

**Issue by EidrianGM** [eandresleon/miARma-seq#3]
Hola Eduardo,

Mirando el report de summary_results, no termino de entender a qué hacen referencia cada una de las columnas. He intentado buscar en los articulos algo que lo explique pero no doy con la tecla. 

Especialmente me escama que el número de _Aligned reads_  sea menor que el de _Assigned reads_.

El analisis está lanzado con la ultima version estable aqui disponible y con los parametros por defecto, usando el alineador Bowtie2.

**Comment by eandresleon** [comment]
Hola Adrian,
En los papers no se explica el summary_results. Esto estaba en al antigua web donde estaba colgado el código y los ejemplo de uso de miARma. Ese dominio "se perdió" y he movido el código aquí y en un futuro (no cercano) meteré el resto.
Lo que si es cierto es que en lso manuales de ayuda sí que aparece esa información. Voy a subirlos ahora (son 2 PDFs), para que los veas.

De todas formas te contesto a lo que te "escama". Eso es normal si trabajas con paired reads, porque usamos featurecounts como fragmentos (las 2 reads pareadas se transforman en un fragmento asignado [Aigned read en el report]). Dependiendo de si usas como parámetro -B o no el numero de assigned read puede llegar a ser menos de la mitad de las aligned reads.
 
Un saludo!

**Comment by EidrianGM** [comment]
Pues en concreto no usamos paired reads, y tenemos especificado "seqtype=Single". ¿Sigue siendo normal en este caso?

**Comment by eandresleon** [comment]
No, eso es más raro. Es cierto que no recuerdo muy bien como alinea bowtie2 (puede que el aligned reads no contenga multimapping, chimeras etc etc), asi que comprueba en los bam realmente lo alineado (samtools flagstat file.bam) y lo cuantificado (ficheros summary dentro de la carpeta bw2_readcount_counts )

**Comment by EidrianGM** [comment]
He podido comprobar que la tabla de Bowtie2_results sale del propio log que saca Bowtie2, que se guarda en stats.txt

Creo que cambiando en el archivo lib/CbBio/RNAseq/Aligner.pm la variable _$aligned_ por _$uniquemapping_ y la cabezera "Aligned reads" por "Uniquely Mapped" todo quedaría mas claro, pero no sé si esto puede afectar a otros analisis con diferentes alineadores.
