### ISSUE TITLE
pre build binaries

### ISSUE THREAD

**Issue by asalimih** [eandresleon/miARma-seq#4]
hello,
Where can I get the miARma 1.7.6 binaries. there is an annoying perl [bug ](https://bitbucket.org/cbbio/miarma/issues/112/de-novo-mirdeep2-problems-cannot-stat)in 1.7.2
I could find the miaRma 1.7.2 [here](https://sourceforge.net/projects/miarma/).

**Comment by eandresleon** [comment]
The code of this github is 1.7.6. You can clone the repo or download it in zip format: https://github.com/eandresleon/miARma-seq/archive/refs/heads/main.zip
